ITMunch/ITMunch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('itmunch/', include('app_itmunch.urls'))
]

ITMunch/app_itmunch/urls.py
from django.urls import path
from . import views

app_name = 'app_itmunch'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('questions/', views.questions_view, name='questions'),
    path('edit/', views.questions_view, name='edit'),
    path('results/', views.search_results, name='search_results'),
    path('delete_user/<int:user_id>/', views.delete_user_view, name='delete_user'),

    #########################################################################
    ### THE CODE BELOW IS NOT USED BUT WAS KEPT TO SHOW WHAT WE WORKED ON ###
    #########################################################################

    path('save_entry/', views.save_nutritionEntry, name='save_entry'), 
    path('load_entry/', views.load_nutritionEntries, name='load_entry'),# todo: add variables I think
    path('delete_entry/', views.delete_nutritionEntry, name='delete_entry'),# todo: add variables I think
    path('add_to_cart/<int:fdcId>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/remove/<int:food_id>/', views.remove_from_cart, name='remove_from_cart'),
]

ITMunch/app_itmunch/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    goal = models.CharField(max_length=20, choices=[('maintain_weight', 'Maintain Weight'), ('lose_weight', 'Lose Weight'), ('gain_weight', 'Gain Weight')])
    gender = models.CharField(max_length=10, choices=[('male', 'Male'), ('female', 'Female')])
    birthday = models.DateField(default='1900-01-01')
    height = models.FloatField(default=0)
    current_weight = models.FloatField(default=0)
    goal_weight = models.FloatField(default=0)
    goal_date = models.DateField(default='1900-01-01')
    activity = models.CharField(max_length=50, choices=[
        ('sedentary', 'Sedentary (little to no exercise)'),
        ('lightly_active', 'Lightly active (light exercise/sports 1-3 days a week)'),
        ('moderately_active', 'Moderately active (moderate exercise/sports 3-5 days a week)'),
        ('very_active', 'Very active (hard exercise/sports 6-7 days a week)'),
        ('extra_active', 'Extra active (very hard exercise/sports & physical job)')
    ], default='sedentary')

class NutritionEntry(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    day = models.DateField()
    daytime = models.CharField(max_length=50, choices=[
        ('breakfast','Breakfast'),
        ('lunch','Lunch'),
        ('dinner','Dinner'),
    ], default='Lunch')
    ingredient = models.CharField(max_length=128, default="")
    weight = models.PositiveIntegerField(default=0)

#########################################################################
### THE CODE BELOW IS NOT USED BUT WAS KEPT TO SHOW WHAT WE WORKED ON ###
#########################################################################

class Food(models.Model):
    name = models.CharField(max_length=100)
    fat = models.FloatField()
    protein = models.FloatField()
    carbohydrates = models.FloatField()
    calories = models.FloatField()
    fdcId = models.IntegerField(unique=True)

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(Food, through='CartItem')

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

ITMunch/app_itmunch/views.py
import datetime
from django import forms
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import *
import re
import requests #anaconda prompt -> conda activate [environment] -> conda install requests

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['goal', 'gender', 'birthday', 'height', 'current_weight', 'goal_weight', 'goal_date', 'activity']
        labels = {
            'birthday': 'Birthday (YYYY-MM-DD)',
            'height': 'Height (Centimeters)',
            'current_weight': 'Current weight (Kilograms)',
            'goal_weight': 'Goal weight (Kilograms)',
            'goal_date': 'Goal date (YYYY-MM-DD)',
        }

class NutritionEntryForm(forms.ModelForm):
    class Meta:
        model = NutritionEntry
        fields = ['day', 'daytime', 'ingredient', 'weight']
        labels = {
            'day': 'The day you ate this food',
            'daytime': 'Time of the day you ate this food',
            'ingredient': 'Name of the ingredient',
            'weight': 'Weight of the ingredient'
        }

class IngredientSearchForm(forms.Form):
    ingredient = forms.CharField(label='Enter Ingredient')

def index(request):
    """Index view for the application.

    Args:
        request (HttpRequest): The request object used to generate this response.
    
    Returns:
        HttpResponse: The rendered index page with profile and calories context.
    """
    
    if not request.user.is_authenticated: # redirect to login if user is not authenticated
        return redirect('app_itmunch:login')
    user = request.user
    profile, created = Profile.objects.get_or_create(user=user) # get or create a profile for the user
    calories = calculate_calories(profile)
    calories_eaten = request.session.get('calories_eaten', 0)
    progress = (calories_eaten / calories) * 100
    breakfast_calories = request.session.get('breakfast_calories', round(calories * 0.25)) # calculate meal calories based on percentages
    lunch_calories = request.session.get('lunch_calories', round(calories * 0.40))
    dinner_calories = request.session.get('dinner_calories', round(calories * 0.35))
    show_tutorial = request.session.pop('show_tutorial', False)

    form = IngredientSearchForm(request.GET or None)
    nutrition_list = []

    if request.method == 'POST': # retrieve the calories and default to 0 if not exist
        calories = float(request.POST.get('calories', 0))
        calories_eaten = request.session.get('calories_eaten', 0)
        meal = request.POST.get('meal') # retrieve the selected meal
        if meal == 'breakfast': # deduct the consumed calories from the respective meals total
            breakfast_calories -= calories
            if breakfast_calories < 0:
                breakfast_calories = 0
        elif meal == 'lunch':
            lunch_calories -= calories
            if lunch_calories < 0:
                lunch_calories = 0
        elif meal == 'dinner':
            dinner_calories -= calories
            if lunch_calories < 0:
                lunch_calories = 0

        calories_eaten += calories # add the consumed calories to the total calories eaten
        request.session['calories_eaten'] = calories_eaten # update the calories eaten and each meal calories
        request.session['breakfast_calories'] = breakfast_calories
        request.session['lunch_calories'] = lunch_calories
        request.session['dinner_calories'] = dinner_calories

        return redirect('app_itmunch:index')

    if form.is_valid():
        ingredient = form.cleaned_data['ingredient']
        nutrition_list = nutrition_list_from_api(inputstring=ingredient, number_of_entries=5)

    return render(request, 'app_itmunch/index.html', {'profile': profile,
                                                      'calories': int(calories),
                                                      'calories_eaten': int(calories_eaten),
                                                      'progress': progress,
                                                      'breakfast_calories': int(breakfast_calories),
                                                      'lunch_calories': int(lunch_calories),
                                                      'dinner_calories': int(dinner_calories),
                                                      'show_tutorial': show_tutorial,
                                                      'form': form,
                                                      'nutrition_list': nutrition_list,})

def login_view(request):
    """Login view for the application.

    Args:
        request (HttpRequest): The request object used to generate this response.

    Returns:
        HttpResponse: The rendered login page with form context.
        HttpResponseRedirect: Redirects to the index page upon successful login.
    """
    
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid(): # authenticate the user with cleaned credentials
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('app_itmunch:index')
    else: # empty authentication form to render the HTML page
        form = AuthenticationForm()
    return render(request, 'app_itmunch/login.html', {'form': form})

def register_view(request):
    """Register view for the application.

    Args:
        request (HttpRequest): The request object used to generate this response.

    Returns:
        HttpResponse: The rendered registration page with form context.
        HttpResponseRedirect: Redirects to the questions page upon successful registration.
    """
    
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.save()
            login(request, user)
            return redirect('app_itmunch:questions')
    else: # empty user creation form to render the HTML page
        form = UserCreationForm()
    return render(request, 'app_itmunch/register.html', {'form': form})

def logout_view(request):
    """Logout view for the application.

    Args:
        request (HttpRequest): The request object used to generate this response.

    Returns:
        HttpResponseRedirect: Redirects to the login page after logout.
    """
    
    logout(request)
    return redirect('app_itmunch:login')


def delete_user_view(request, user_id):
    """Delete user view for the application.

    Args:
        request (HttpRequest): The request object used to generate this response.
        user_id (int): The ID of the user to delete.

    Returns:
        HttpResponseRedirect: Redirects to the login page after user deletion.
    """
    
    user = get_object_or_404(User, id=user_id) # get the user object by ID, if not found return 404
    if request.user == user or request.user.is_staff: # check if the user making the request is the user to be deleted or has appropriate permissions
        user.delete()  # delete the user
        logout(request)  # log out the current session
        return redirect('app_itmunch:login')  # redirect to the login page
    else:
        return redirect('app_itmunch:index')  # redirect to index page if unauthorized

def questions_view(request):
    """Questions view for the application.

    Args:
        request (HttpRequest): The request object used to generate this response.

    Returns:
        HttpResponse: The rendered questions page with form context.
        HttpResponseRedirect: Redirects to the index page upon successful form submission.
    """
    
    if not request.user.is_authenticated: # redirect to login if user is not authenticated
        return redirect('app_itmunch:login')
    user = request.user
    profile, created = Profile.objects.get_or_create(user=user) # get or create a profile for the user
    if request.method == 'POST': # create a form with POST data and the user's profile instance
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('app_itmunch:index')
    else: # empty profile form to render the HTML page
        form = ProfileForm(instance=profile)
    if created:  # render questions page if the profile was just created
        request.session['show_tutorial'] = True # show tutorial if the profile was just created
        return render(request, 'app_itmunch/questions.html', {'form': form})
    else:  # render edit profile page if the profile already exists
        return render(request, 'app_itmunch/edit.html', {'form': form})

def calculate_calories(profile):
    """Calculate daily calorie needs based on the profile.

    Args:
        profile (Profile): The user's profile containing weight, height, age, gender, activity level, and goal.

    Returns:
        int: The calculated daily calorie needs.
    """

    weight = float(profile.current_weight)
    height = float(profile.height)
    age = (datetime.date.today() - profile.birthday).days // 365 # calculate age based on today date
    if profile.gender == 'male': # calculate basal metabolic rate using Mifflin-St Jeor formula
        bmr = 10 * weight + 6.25 * height - 5 * age + 5
    else:
        bmr = 10 * weight + 6.25 * height - 5 * age - 161
    multiplier = { # activity level multipliers
        'sedentary': 1.2,
        'lightly_active': 1.375,
        'moderately_active': 1.55,
        'very_active': 1.725,
        'extra_active': 1.9
    }
    calories = int(bmr * multiplier[profile.activity]) # calculate calories based on activity level

ITMunch/app_itmunch/templates/app_itmunch/cart.html
<!-- ####################################################################
### THE CODE BELOW IS NOT USED BUT WAS KEPT TO SHOW WHAT WE WORKED ON ###
##################################################################### -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Cart</title>
</head>
<body>

    <main>
        <h2>Items in Your Cart</h2>

        {% if cart.items.exists %}
            <table>
                <thead>
                    <tr>
                        <th>Food Item</th>
                        <th>Fat (g)</th>
                        <th>Protein (g)</th>
                        <th>Carbohydrates (g)</th>
                        <th>Calories</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cart_item in cart_items %}
                        <tr>
                            <td>{{ cart_item.food.name }}</td>
                            <td>{{ cart_item.food.fat }}</td>
                            <td>{{ cart_item.food.protein }}</td>
                            <td>{{ cart_item.food.carbohydrates }}</td>
                            <td>{{ cart_item.food.calories }}</td>
                            <td>
                                <form action="{% url 'app_itmunch:remove_from_cart' cart_item.food.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit">Remove</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>Your cart is empty.</p>
        {% endif %}
    </main>

    <footer>
        <p>&copy; 2024 ITMunch</p>
    </footer>
</body>
</html>

ITMunch/app_itmunch/templates/app_itmunch/edit.html
{% extends "app_itmunch/layout1.html" %}

{% block title %}Edit Profile{% endblock %}

{% block body %}
<div class="edit">
    <div>
    <h1>Edit Profile</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button id="button_login" type="submit">Save Changes</button>
    </form>
    </div>
</div>

{% endblock %}

ITMunch/app_itmunch/templates/app_itmunch/index.html
{% extends "app_itmunch/layout1.html" %}

{% block title %}Index{% endblock %}

{% block body %}
    <div class="index_container">
        <div class="index_flexbox">
            <h2>Calendar</h2>
            <div class="container mt-5">
                <div id="calendar"></div>
            </div>
        </div>
        <div class="index_flexbox">
            <h1>Welcome, {{ request.user.username }}!</h1>
            <p>Daily calorie intake: {{ calories }} kcal</p>
            <div class="progress" role="progressbar" aria-label="Success example" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="height: 30px">
                <div id="progress-bar-eaten" class="progress-bar bg-dark"></div>
            </div>
            <div>{{ calories_eaten }} kcal eaten</div>
            <div class="middle_container">
                <div class="middle_box" style="background-color: #B0DBB2;">
                    <h6>Breakfast</h6>
                    <h5>{{ breakfast_calories }} kcal</h5>
                </div>
                <div class="middle_box" style="background-color: #558D57;">
                    <h6>Lunch</h6>
                    <h5>{{ lunch_calories }} kcal</h5>
                </div>
                <div class="middle_box" style="background-color: #38793B;">
                    <h6>Dinner</h6>
                    <h5>{{ dinner_calories }} kcal</h5>
                </div>
            </div>
        </div>
        <div class="index_flexbox">
            <h2>Add Food</h2>
            <br>
            <form method="GET" action="{% url 'app_itmunch:index' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button id="index_button" type="submit">Search</button>
            </form>

            {% for item in nutrition_list %}
                <br>    
                <li>
                    <span>Name: {{ item.name }}</span>
                    <span>Fat: {{ item.fat }}</span>
                    <span>Protein: {{ item.protein }}</span>
                    <span>Carbohydrates: {{ item.carbohydrates }}</span>
                    <span>Calories: {{ item.calories }}</span>

                    <form method="POST" action="{% url 'app_itmunch:index' %}">
                        {% csrf_token %}
                        <input type="hidden" name="calories" value="{{ item.calories }}">
                        <select name="meal" required>
                            <option value="" disabled selected>Select Meal</option>
                            <option value="breakfast">Breakfast</option>
                            <option value="lunch">Lunch</option>
                            <option value="dinner">Dinner</option>
                        </select>
                        <button id="index_button" type="submit">Add</button>
                    </form>
                </li>
            {% endfor %}
        </div>
    </div>

    <div id="myModal" class="modal">
        <div class="modal-content">
            <h1>How to use ITMunch?</h1>
            <div class="tuto active">
                <h2>Ready for a brand new start!</h2>
                <p>ITMunch is a website that enables you to track your daily nutrition intake, set dietary goals, and receive personalized recommendations based on your nutritional needs.</p>
            </div>
            <div class="tuto">
                <h2>Follow your progress monthly!</h2>
                <p>For every meal of your day, you can add the food you eat to follow your calorie intake. Check the calendar!</p>
            </div>
            <div class="tuto">
                <h2>Add the food you eat daily!</h2>
                <p>To add new food to your meals, search its name and add it to the corresponding meal (breakfast, lunch or dinner) by clicking on the "add" button.</p>
            </div>
            <button id="next">Next</button>
            <button id="close" style="display:none">Close</button>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.0/main.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Creation of the calendar
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth'
            });
            calendar.render();

            
            // Pop-up tutorial page when first connection
            window.onload = function() {
                var show_tutorial = "{{ show_tutorial }}";
                if (show_tutorial == "True") {
                    document.getElementById('myModal').style.display = 'block';
                }

                var modal = document.getElementById('myModal');
                var tutos = document.querySelectorAll('.tuto');
                var nextButton = document.querySelector('#next');
                var closeButton = document.querySelector('#close');
                let currentTutoIndex = 0;

                // When next button is clicked, display the next tutorial div
                nextButton.onclick = function() {
                    const currentTuto = tutos[currentTutoIndex];
                    currentTuto.classList.remove('active');
                    currentTutoIndex++;
                    if (currentTutoIndex < tutos.length) {
                        tutos[currentTutoIndex].classList.add('active');
                    }
                    if (currentTutoIndex === tutos.length - 1) {
                        nextButton.style.display = 'none';
                        closeButton.style.display = 'block';
                    }
                }

                // Close the modal when close button is clicked
                closeButton.onclick = function() {
                    modal.style.display = 'none';
                }
            }
            const progressBar = document.querySelector('#progress-bar-eaten');
            progressBar.style.width = "{{ progress }}%";
        });
    </script>

{% endblock %}

ITMunch/app_itmunch/templates/app_itmunch/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'app_itmunch/styles.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'app_itmunch/script.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ITMunch</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="index.html">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Calendar</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="add_recipe.html">Recipes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Settings</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

ITMunch/app_itmunch/templates/app_itmunch/layout1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.0/main.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link href="{% static 'app_itmunch/styles.css' %}" rel="stylesheet">
    <script src="{% static 'app_itmunch/script.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-custom">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'app_itmunch:index' %}">ITMunch</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'app_itmunch:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app_itmunch:edit' %}">Edit Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app_itmunch:logout' %}">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app_itmunch:delete_user' user.id %}"
                onclick="return confirm('Are you sure you want to delete your account?');">
                    Delete User
                </a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

ITMunch/app_itmunch/templates/app_itmunch/layout2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link href="{% static 'app_itmunch/styles.css' %}" rel="stylesheet">
    <script src="{% static 'app_itmunch/script.js' %}"></script>
    
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-custom">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ITMunch</a>
            <ul class="navbar-nav">
            </ul>
          </div>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

ITMunch/app_itmunch/templates/app_itmunch/login.html
{% extends "app_itmunch/layout2.html" %}

{% block title %}Login{% endblock %}

{% block body %}
    <div class="login">
        <div>
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button id="button_login" type="submit">Login</button>
    </form>
    <p>Don't have an account? <a href="{% url 'app_itmunch:register' %}">Register here</a></p>
</div>
</div>
{% endblock %}

ITMunch/app_itmunch/templates/app_itmunch/register.html
{% extends "app_itmunch/layout2.html" %}

{% block title %}Register{% endblock %}

{% block body %}
    <div class="register">
        <div>
            <h1>Register</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button id="button_login" type="submit">Register</button>
            </form>
            <p>Already have an account? <a href="{% url 'app_itmunch:login' %}">Login here</a></p>
        </div>
    </div>
{% endblock %}

ITMunch/app_itmunch/templates/app_itmunch/search.html
<!-- ####################################################################
### THE CODE BELOW IS NOT USED BUT WAS KEPT TO SHOW WHAT WE WORKED ON ###
##################################################################### -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ingredient Search Results</title>
</head>
<body>
    <h1>Search for Nutritional Data</h1>
    <form method="GET" action="{% url 'app_itmunch:search_results' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Search</button>
    </form>

    {% for item in nutrition_list %}
        <li>
            <span>Name: {{ item.name }}</span>
            <span>Fat: {{ item.fat }}</span>
            <span>Protein: {{ item.protein }}</span>
            <span>Carbohydrates: {{ item.carbohydrates }}</span>
            <span>Calories: {{ item.calories }}</span>
            {% if request.user.is_authenticated %}
                <a href="{% url 'app_itmunch:add_to_cart' item.fdcId %}">Add to Cart</a>
            {% endif %}
        </li>
    {% endfor %}

    {% if nutrition_list %}
        <h2>Nutrient Data:</h2>
        <ul>
            {% for item in nutrition_list %}
                <li>Name: {{ item.name }}</li>
                <li>Fat: {{ item.fat }}</li>
                <li>Protein: {{ item.protein }}</li>
                <li>Carbohydrates: {{ item.carbohydrates }}</li>
                <li>Calories: {{ item.calories }}</li>
                <br>
            {% endfor %}
        </ul>
    {% else %}
        <p>No nutrient data found.</p>
    {% endif %}
</body>
</html>